-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgLxQ1kiNcMswkkORF
F5Ga0kEQeR543EiOiRvHKRjYYlCgCgYIKoZIzj0DAQehRANCAAQwYQwicLlcusbG
1yxyMCXHVpHl9mQXge4jSyvcgjJZFT1Jfu1cR2EC8jtpFOTzVk1F5GEZ+x9ALHO1
Ow1UfZGE
-----END PRIVATE KEY-----